# Generated by Django 5.2.16 on 2026-08-08 15:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
        ('staff', '0006_alter_staffprofile_photo'),
        ('students', '0006_student_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(default=1)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('due_date', models.DateField()),
                ('is_fully_paid', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('receipt_no', models.CharField(editable=False, max_length=30, unique=True)),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fee_payment.feeinstallment')),
                ('paid_by_staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_payments_recorded', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_fee_structures', to='branches.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_structures', to='fee_payment.feecategory')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_fee_structures', to='students.class')),
            ],
            options={
                'ordering': ['branch', 'class_name', 'category'],
                'unique_together': {('branch', 'class_name', 'category', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_reason', models.CharField(blank=True, max_length=255)),
                ('final_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fee_structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='fee_payment.feestructure')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_assignments', to='students.student')),
            ],
            options={
                'unique_together': {('student', 'fee_structure')},
            },
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fee_payment.studentfeeassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='feeinstallment',
            unique_together={('assignment', 'installment_number')},
        ),
    ]
