# Generated by Django 5.2.16 on 2026-08-09 05:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('fee_payment', '0001_initial'),
        ('staff', '0006_alter_staffprofile_photo'),
        ('students', '0006_student_student_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('fee_due', 'Fee Due'), ('payment_recorded', 'Payment Recorded'), ('due_reminder', 'Due Reminder'), ('overdue', 'Overdue Notice')], db_index=True, max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], db_index=True, max_length=10)),
                ('recipient', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_success', models.BooleanField(db_index=True, default=False)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='feecategory',
            options={'ordering': ['name'], 'verbose_name': 'Fee Category', 'verbose_name_plural': 'Fee Categories'},
        ),
        migrations.AlterModelOptions(
            name='feeinstallment',
            options={'ordering': ['due_date'], 'verbose_name': 'Fee Installment', 'verbose_name_plural': 'Fee Installments'},
        ),
        migrations.AlterModelOptions(
            name='feepayment',
            options={'ordering': ['-paid_on'], 'verbose_name': 'Fee Payment', 'verbose_name_plural': 'Fee Payments'},
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['branch', 'class_name', 'category'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.AlterModelOptions(
            name='studentfeeassignment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Student Fee Assignment', 'verbose_name_plural': 'Student Fee Assignments'},
        ),
        migrations.AddField(
            model_name='feestructure',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('half_yearly', 'Half Yearly'), ('yearly', 'Yearly')], db_index=True, default='yearly', help_text='Determines how many installments are auto-generated per assignment.', max_length=20),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='notify_parent',
            field=models.BooleanField(default=True, help_text='Send fee notifications to parent.'),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='parent_email',
            field=models.EmailField(blank=True, help_text='Leave blank to use student record email.', max_length=254),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='parent_phone',
            field=models.CharField(blank=True, help_text='Leave blank to use student record phone.', max_length=20),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='feecategory',
            name='name',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='feeinstallment',
            name='due_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='feeinstallment',
            name='is_fully_paid',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], db_index=True, default='cash', max_length=20),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='paid_on',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='receipt_no',
            field=models.CharField(db_index=True, editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='feepayment',
            name='transaction_ref',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.CharField(db_index=True, max_length=9),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='studentfeeassignment',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['due_date', 'is_fully_paid'], name='fee_payment_due_dat_b7c4b9_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['assignment', 'is_fully_paid'], name='fee_payment_assignm_c87549_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['receipt_no', 'paid_on'], name='fee_payment_receipt_9265a3_idx'),
        ),
        migrations.AddIndex(
            model_name='feepayment',
            index=models.Index(fields=['installment', 'paid_on'], name='fee_payment_install_2b4105_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['academic_year', 'is_active'], name='fee_payment_academi_9a6988_idx'),
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['branch', 'class_name', 'is_active'], name='fee_payment_branch__29d81b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['student', 'is_active'], name='fee_payment_student_df2938_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['fee_structure', 'is_active'], name='fee_payment_fee_str_297a6b_idx'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='fee_payment.studentfeeassignment'),
        ),
        migrations.AddField(
            model_name='notificationlog',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='fee_payment.feeinstallment'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['assignment', 'notification_type', 'sent_at'], name='fee_payment_assignm_70da1a_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['channel', 'is_success', 'sent_at'], name='fee_payment_channel_28df44_idx'),
        ),
    ]
