# Generated by Django 5.2.16 on 2026-08-09 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_payment', '0002_notificationlog_alter_feecategory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeeassignment',
            name='start_date',
            field=models.DateField(blank=True, help_text='Leave blank to use the Fee Structure start date. Set this for Day Care students who join on a specific date.', null=True),
        ),
    ]
