# Generated by Django 5.2.16 on 2026-08-09 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_payment', '0003_studentfeeassignment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Date when the first installment is due. All subsequent due dates are calculated from this.'),
        ),
    ]
