# Generated by Django 5.2.16 on 2026-08-26 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee_payment', '0005_feecategory_created_by_feecategory_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['branch', 'group', 'category'], 'verbose_name': 'Fee Structure', 'verbose_name_plural': 'Fee Structures'},
        ),
        migrations.RemoveIndex(
            model_name='feestructure',
            name='fee_payment_branch__29d81b_idx',
        ),
    ]
