# Generated by Django 5.2.16 on 2026-08-26 05:44
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('branches', '0002_alter_branch_options_branch_updated_at_and_more'),
        ('fee_payment', '0006_alter_feestructure_options_and_more'),
        ('students', '0010_group_alter_class_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]
    operations = [
        migrations.AddField(
            model_name='feestructure',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Leave blank for a fee that applies regardless of group.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='group_fee_structures', to='students.group'),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('branch', 'group', 'category', 'academic_year')},
        ),
        migrations.RemoveField(
            model_name='feestructure',
            name='class_name',
        ),
        migrations.AddIndex(
            model_name='feestructure',
            index=models.Index(fields=['branch', 'group', 'is_active'], name='fee_payment_branch__bdb124_idx'),
        ),
    ]