# Generated by Django 5.2.16 on 2026-09-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_payment', '0008_additionalcharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeeassignment',
            name='held_on',
            field=models.DateField(blank=True, editable=False, help_text='Auto-set to today when the assignment is switched to inactive/hold.', null=True),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='hold_reason',
            field=models.CharField(blank=True, help_text='Why this assignment is on hold. Shown to staff/parents when is_active is False.', max_length=255),
        ),
        migrations.AddField(
            model_name='studentfeeassignment',
            name='resumed_on',
            field=models.DateField(blank=True, editable=False, help_text='Auto-set to today when the assignment is switched back to active.', null=True),
        ),
    ]
