# Generated by Django 5.2.16 on 2026-10-08 08:34

import datetime
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_payment', '0010_additionalcharge_created_at_and_more'),
        ('students', '0012_alter_group_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_period_days', models.PositiveIntegerField(default=30, help_text="Default number of days' written notice required before a deposit becomes refundable. Can be overridden per deposit.")),
                ('terms_text', models.TextField(default="1. The deposit collected at admission is fully refundable when the student leaves the school, subject to {notice_period} days' written notice being submitted to the school office in advance.\n\n2. The refund will be processed within {notice_period} days of the notice date, after adjusting any outstanding fees, dues, or damages against the deposit amount.\n\n3. No deposit will be refunded without prior written notice from the parent/guardian.\n\n4. The deposit does not carry any interest for the duration it is held.\n\n5. In case of damage to school property attributable to the student, the cost of repair/replacement will be deducted from the deposit before refund.", help_text='Use {notice_period} as a placeholder — it is filled in with the value above when displayed.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Deposit Terms & Conditions',
                'verbose_name_plural': 'Deposit Terms & Conditions',
            },
        ),
        migrations.CreateModel(
            name='SecurityDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('receipt_no', models.CharField(db_index=True, editable=False, max_length=30, unique=True)),
                ('paid_on', models.DateField(default=datetime.date.today)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], default='cash', max_length=20)),
                ('transaction_ref', models.CharField(blank=True, max_length=100)),
                ('notice_period_days', models.PositiveIntegerField(default=30, help_text="Days' written notice required before this deposit becomes refundable. Pre-filled from the current Deposit Policy at creation, but editable per deposit.")),
                ('notice_given_on', models.DateField(blank=True, help_text='Date the parent/guardian submitted written notice of leaving.', null=True)),
                ('is_refunded', models.BooleanField(db_index=True, default=False)),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Any amount withheld before refund (damages, outstanding dues, etc.).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('deduction_reason', models.CharField(blank=True, max_length=255)),
                ('refunded_on', models.DateField(blank=True, null=True)),
                ('refund_mode', models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('card', 'Card')], max_length=20)),
                ('refund_transaction_ref', models.CharField(blank=True, max_length=100)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_deposits', to='students.student')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Security Deposit',
                'verbose_name_plural': 'Security Deposits',
                'ordering': ['-paid_on'],
            },
        ),
    ]
