# Generated by Django 5.2.16 on 2026-07-29 05:45

import django.core.validators
import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0004_experiencehistory_promotionhistory_salaryincrement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('student_class', models.CharField(max_length=50)),
                ('mother_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('father_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('mother_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('father_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mother_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('father_occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('mother_photo', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), students.models.validate_document_size])),
                ('father_photo', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), students.models.validate_document_size])),
                ('photo', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), students.models.validate_document_size])),
                ('medical_documents', models.FileField(blank=True, null=True, upload_to=students.models.student_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), students.models.validate_document_size])),
                ('address', models.TextField()),
                ('admission_date', models.DateField(auto_now_add=True)),
                ('assigned_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_assigned', to='staff.staffprofile')),
            ],
        ),
    ]
