# Generated by Django 5.2.16 on 2026-08-01 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_class_name_alter_class_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Mark student as active or inactive'),
        ),
    ]
