# Generated by Django 5.2.16 on 2026-08-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='inactive_date',
            field=models.DateField(blank=True, help_text='Date when student became inactive', null=True),
        ),
    ]
