# Generated by Django 5.2.16 on 2026-08-03 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
        ('students', '0005_student_inactive_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
    ]
