# Generated by Django 5.2.16 on 2026-08-13 06:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_educationrecord_options_and_more'),
        ('students', '0007_alter_student_options_remark_statushistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, help_text="e.g. 'Promotion', 'Transferred', 'Repeated year'", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_history', to='students.student')),
                ('student_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.class')),
            ],
            options={
                'verbose_name_plural': 'Class histories',
                'ordering': ['-changed_on', '-id'],
            },
        ),
    ]
