# Generated by Django 5.2.16 on 2026-08-26 05:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_staffprofile_blood_group'),
        ('students', '0009_student_created_at_student_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RED', 'Red'), ('GREEN', 'Green'), ('ORANGE', 'Orange')], max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='classhistory',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_class',
        ),
        migrations.RemoveField(
            model_name='classhistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='classhistory',
            name='student',
        ),
        migrations.RemoveField(
            model_name='student',
            name='assigned_teacher',
        ),
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='students.group'),
        ),
        migrations.CreateModel(
            name='GroupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_on', models.DateField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, help_text="e.g. 'Initial placement', 'Reassessment', 'Progress review'", max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_history', to='students.student')),
            ],
            options={
                'verbose_name_plural': 'Group histories',
                'ordering': ['-changed_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GroupStaffAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_on', models.DateField(default=django.utils.timezone.now)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='students.group')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_assignments', to='staff.staffprofile')),
            ],
            options={
                'ordering': ('-assigned_on',),
            },
        ),
        migrations.CreateModel(
            name='StudentTherapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, help_text="e.g. '3x/week'", max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapy_sessions', to='staff.staffprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapy_enrollments', to='students.student')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.therapy')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
        migrations.RemoveField(
            model_name='student',
            name='therapies',
        ),
        migrations.AddField(
            model_name='student',
            name='therapies',
            field=models.ManyToManyField(blank=True, related_name='students', through='students.StudentTherapy', to='students.therapy'),
        ),
    ]