# Generated by Django 5.2.16 on 2026-08-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee_payment', '0007_alter_feestructure_unique_together_and_more'),
        ('students', '0010_group_alter_class_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
        migrations.DeleteModel(
            name='ClassHistory',
        ),
        migrations.AddConstraint(
            model_name='groupstaffassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('group', 'staff'), name='unique_active_group_staff'),
        ),
        migrations.AddConstraint(
            model_name='studenttherapy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('student', 'therapy'), name='unique_active_student_therapy'),
        ),
    ]
