# Generated by Django 5.2.16 on 2026-07-22 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_documents'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperienceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_history', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PromotionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_designation', models.CharField(max_length=100)),
                ('new_designation', models.CharField(max_length=100)),
                ('promotion_date', models.DateField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='staff.staffprofile')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryIncrement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('increment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-year'],
                'unique_together': {('staff', 'year')},
            },
        ),
    ]
