# Generated by Django 5.2.16 on 2026-08-05 18:10

import django.core.validators
import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_experiencehistory_promotionhistory_salaryincrement'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='photo',
            field=models.FileField(blank=True, upload_to=staff.models.staff_document_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png']), staff.models.validate_document_size]),
        ),
    ]
