# Generated by Django 5.2.16 on 2026-08-05 21:22

import django.core.validators
import staff.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staffprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=staff.models.staff_document_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), staff.models.validate_document_size]),
        ),
    ]
