# Generated by Django 5.2.16 on 2026-08-10 19:46

import django.core.validators
import django.utils.timezone
import staff.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_alter_staffprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educationrecord',
            options={'ordering': ('-passing_year',), 'verbose_name': 'Education Record', 'verbose_name_plural': 'Education Records'},
        ),
        migrations.AlterModelOptions(
            name='experiencehistory',
            options={'ordering': ('-start_date',), 'verbose_name': 'Experience History', 'verbose_name_plural': 'Experience Histories'},
        ),
        migrations.AlterModelOptions(
            name='promotionhistory',
            options={'ordering': ('-promotion_date',), 'verbose_name': 'Promotion History', 'verbose_name_plural': 'Promotion Histories'},
        ),
        migrations.AlterModelOptions(
            name='salaryincrement',
            options={'ordering': ['-year'], 'verbose_name': 'Salary Increment', 'verbose_name_plural': 'Salary Increments'},
        ),
        migrations.AlterModelOptions(
            name='staffdocument',
            options={'ordering': ('-uploaded_at',), 'verbose_name': 'Staff Document', 'verbose_name_plural': 'Staff Documents'},
        ),
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'ordering': ('employee_id',), 'verbose_name': 'Staff Profile', 'verbose_name_plural': 'Staff Profiles'},
        ),
        migrations.AddField(
            model_name='promotionhistory',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], default='', max_length=1),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='employee_id',
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=staff.models.staff_document_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png']), staff.models.validate_document_size]),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['department', 'is_active'], name='staff_staff_departm_017d93_idx'),
        ),
        migrations.AddIndex(
            model_name='staffprofile',
            index=models.Index(fields=['joining_date'], name='staff_staff_joining_4fb423_idx'),
        ),
    ]
