# Generated by Django 5.2.16 on 2026-08-14 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_alter_educationrecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Edited At'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_edits', to=settings.AUTH_USER_MODEL, verbose_name='Last Edited By'),
        ),
    ]
