# Generated by Django 5.2.16 on 2026-08-14 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_staffprofile_edited_at_staffprofile_edited_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='edited_at',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='edited_by',
        ),
    ]
