# Generated by Django 5.2.16 on 2026-08-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_educationrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
