# Generated by Django 5.2.16 on 2026-08-14 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('object_id', models.PositiveIntegerField()),
                ('object_repr', models.CharField(help_text='Human-readable name of the object at the time of change', max_length=255)),
                ('field_changes', models.JSONField(blank=True, default=dict, help_text='Dictionary of changed fields with old/new values')),
                ('snapshot', models.JSONField(blank=True, default=dict, help_text='Full object snapshot after the change (optional)')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Action By')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-action_time'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-action_time'], name='audit_log_a_content_238f1c_idx'), models.Index(fields=['user', '-action_time'], name='audit_log_a_user_id_b39338_idx'), models.Index(fields=['action', '-action_time'], name='audit_log_a_action_97f378_idx')],
            },
        ),
    ]
