# Generated by Django 5.2.16 on 2026-08-10 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_alter_user_groups'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('branches', '0002_alter_branch_options_branch_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('email',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='accessible_branches',
            field=models.ManyToManyField(blank=True, help_text='Additional branches this user can access. For System Admin, leave empty (all branches are accessible).', related_name='authorized_users', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Primary / home branch for this user.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_users', to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('FINANCE_ADMIN', 'Finance Admin'), ('BRANCH_ADMIN', 'Branch Admin'), ('STAFF', 'Staff')], db_index=True, default='STAFF', help_text="Determines the user's permissions across the system.", max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['branch', 'is_active'], name='accounts_us_branch__3bd875_idx'),
        ),
    ]
